db: &db
  url: jdbc:postgresql://localhost:5432/db
  user: admin
  username: admin
  password: admin

server:
  port: 9000

spring:
  security:
    user:
      name: admin
      password: admin

  datasource: &datasource
    <<: *db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
      cache.use_second_level_cache: true
      jdbc.lob.non_contextual_creation: true
      properties.hibernate.temp.use_jdbc_metadata_defaults: false

  flyway:
    <<: *db
    enabled: true
    locations: classpath:db/migration/pg
    schemas: public
    baseline-on-migrate: true