debug: false

db: &db
  url: jdbc:postgresql://localhost:5432/db
  user: admin
  username: admin
  password: admin

server:
  port: 9000

spring:
  security:
    user:
      name: admin
      password: admin

  datasource: &datasource
    <<: *db
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        cache.use_second_level_cache: false
        jdbc.lob.non_contextual_creation: true

  flyway:
    <<: *db
    enabled: true
    locations: classpath:db/migration/pg
    schemas: public
    baseline-on-migrate: true